"""
Phase 1: Data Exploration Script
Explores PMC_Patients_clean.csv, icd_10_codes.csv, and icd_10_embeddings.npy
Outputs data/SCHEMA.md with full documentation.
"""
import pandas as pd
import numpy as np
import os
import json
from pathlib import Path

DATA_DIR = Path(__file__).parent.parent / "data"
OUTPUT_FILE = DATA_DIR / "SCHEMA.md"


def explore_patients():
    print("\n=== PMC_Patients_clean.csv ===")
    df = pd.read_csv(DATA_DIR / "PMC_Patients_clean.csv", nrows=100)
    print(f"Columns: {list(df.columns)}")
    print(f"Dtypes:\n{df.dtypes}")
    print(f"\nSample row:\n{df.iloc[0].to_dict()}")
    print(f"\nAge stats: {df['age'].describe().to_dict()}")
    print(f"Gender counts: {df['gender'].value_counts().to_dict()}")

    # Get total row count
    total = sum(1 for _ in open(DATA_DIR / "PMC_Patients_clean.csv")) - 1
    print(f"Total rows: {total}")
    return df, total


def explore_icd10():
    print("\n=== icd_10_codes.csv ===")
    df = pd.read_csv(DATA_DIR / "icd_10_codes.csv", nrows=100)
    print(f"Columns: {list(df.columns)}")
    print(f"Dtypes:\n{df.dtypes}")
    print(f"\nSample row:")
    row = df.iloc[0]
    print(f"  icd_10_code: {row['icd_10_code']}")
    print(f"  description: {row['description']}")
    print(f"  embedded_description (first 100 chars): {str(row['embedded_description'])[:100]}")

    total = sum(1 for _ in open(DATA_DIR / "icd_10_codes.csv")) - 1
    print(f"Total rows: {total}")
    return df, total


def explore_embeddings():
    print("\n=== icd_10_embeddings.npy ===")
    arr = np.load(DATA_DIR / "icd_10_embeddings.npy")
    print(f"Shape: {arr.shape}")
    print(f"Dtype: {arr.dtype}")
    print(f"Min: {arr.min():.4f}, Max: {arr.max():.4f}, Mean: {arr.mean():.4f}")
    print(f"Sample vector (first 10 dims): {arr[0][:10]}")
    return arr


def write_schema(patient_df, patient_total, icd_df, icd_total, emb_arr):
    schema = f"""# MedTrace Data Schema

Generated by explore_data.py

## PMC_Patients_clean.csv

**Total rows**: {patient_total:,}

### Columns

| Column | Type | Description | Sample |
|--------|------|-------------|--------|
| patient_id | int | Sequential row index (0-based) | 0, 1, 2 |
| patient_uid | str | Unique patient identifier (format: XXXXXXX-N) | 7665777-1 |
| patient_note | str | Full clinical case note text | "This 60-year-old male..." |
| age | float/int | Patient age in years | 60, 39, 45 |
| gender | str | Patient gender (M/F) | M, F |

**Age range**: {patient_df['age'].min()} – {patient_df['age'].max()}
**Gender distribution (first 100)**: {patient_df['gender'].value_counts().to_dict()}

---

## icd_10_codes.csv

**Total rows**: {icd_total:,}

### Columns

| Column | Type | Description | Sample |
|--------|------|-------------|--------|
| embedded_description | str (JSON array) | Pre-computed embedding vector as JSON string | "[0.0102, -0.0089, ...]" |
| icd_10_code | str | ICD-10 code | A00.0, E11.9, I10 |
| description | str | Human-readable description | "Cholera due to Vibrio cholerae..." |

**Note**: The `embedded_description` column contains the same embeddings as `icd_10_embeddings.npy`.

---

## icd_10_embeddings.npy

**Shape**: {emb_arr.shape}
**Dtype**: {emb_arr.dtype}
**Min**: {emb_arr.min():.4f}
**Max**: {emb_arr.max():.4f}
**Mean**: {emb_arr.mean():.4f}

**Alignment**: {emb_arr.shape[0]} rows matches icd_10_codes.csv ({icd_total} rows) ✓

**Embedding dimension**: {emb_arr.shape[1]}
**Model origin**: NOT nomic-embed-text-v1.5 (which produces 768-dim). Likely text-embedding-ada-002 or similar (1536-dim).

---

## Architectural Notes

### Cross-model compatibility
The pre-computed ICD-10 embeddings are 1536-dim and from an unknown model.
nomic-embed-text-v1.5 produces 768-dim embeddings.
**Strategy**: Re-embed top ~10,000 ICD-10 descriptions with nomic-embed-text-v1.5 during index building
for cross-model consistency. This ensures patient note embeddings and ICD-10 embeddings live in the same vector space.

### Patient data size
167K patient notes at ~500 tokens avg = ~83M tokens total.
At runtime, only the pre-indexed subset (~15K patients) is loaded.

### Index files to build
- `indexes/patient_faiss.index` — FAISS IndexFlatIP, 768-dim (nomic-embed-text)
- `indexes/patient_metadata.json` — list of {{patient_uid, age, gender, snippet}}
- `indexes/patients_subset.parquet` — subsampled patient dataframe
- `indexes/bm25_index.pkl` — rank_bm25 BM25Okapi, 15K patient notes
- `indexes/icd10_faiss.index` — FAISS IndexFlatIP, 768-dim (nomic-embed-text re-embedded)
- `indexes/icd10_mapping.json` — index → {{code, description}}
"""
    with open(OUTPUT_FILE, "w") as f:
        f.write(schema)
    print(f"\nSchema written to {OUTPUT_FILE}")


if __name__ == "__main__":
    patient_df, patient_total = explore_patients()
    icd_df, icd_total = explore_icd10()
    emb_arr = explore_embeddings()

    # Verify alignment
    print(f"\n=== Alignment Check ===")
    print(f"icd_10_codes.csv rows: {icd_total}")
    print(f"icd_10_embeddings.npy rows: {emb_arr.shape[0]}")
    if icd_total == emb_arr.shape[0]:
        print("✓ Aligned perfectly")
    else:
        print(f"⚠ MISMATCH: {icd_total} vs {emb_arr.shape[0]}")

    write_schema(patient_df, patient_total, icd_df, icd_total, emb_arr)
    print("\nPhase 1 complete. Proceed to Phase 2: build indexes.")
